# Generated by Django 5.0.1 on 2024-01-18 20:46

import django.db.models.deletion
from django.db import migrations, models

def insert_initial_data(apps, schema_editor):
    StockModel = apps.get_model('simulator', 'Materials')
    UserStockModel = apps.get_model('simulator', 'UserStocks')

    stock_to_insert = [
        {'stockname': 'AAPL'},
        {'stockname': 'MSFT'},
        {'stockname': 'AMZN'},
        {'stockname': 'FB'},
        {'stockname': 'TSLA'},
        {'stockname': 'JNJ'},
        {'stockname': 'KO'},
        {'stockname': 'GE'}
    ]

    for data in stock_to_insert:
        StockModel.objects.create(**data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('userpasswd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.CharField(max_length=255)),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.materials')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=255)),
                ('stock_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.CharField(max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='simulator.customuser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('stockId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.materials')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.customuser')),
            ],
        ),
        migrations.RunPython(insert_initial_data),
    ]
